### ISSUE TITLE
Resizing the browser window does not trigger a repaint of the background stars

### ISSUE THREAD

**Issue by toxoplasmotic** [SeanECogan/mini-orbits#2]
Start the game with a small browser window, and then maximize the window. Notice the stars no longer extend to the edges of the window.

Placement of A/R/S still works across the whole screen, though.

**Comment by SeanECogan** [comment]
Good catch! Should be an easy fix, I'll probably take care of it tonight.

**Comment by SeanECogan** [comment]
Closed in PR #3 .
